### ISSUE TITLE
Rumble assignment not found

### ISSUE THREAD

**Issue by smguth** [KeyPuncher/Easy-Pair#1]
Hello I cannot find how to assign the rumble feature mentioned in the website.   I have attempted this with a joycon so far.  

Link a controller's rumble to one or more XInput devices' Force Feedback output

Rumble on assignment use

Is is possible to have motion be an input as well?

**Comment by KeyPuncher** [comment]
This ended up in the wrong repository, should've been here https://github.com/KeyPuncher/WiinUPro/issues

However, since you are using a joy-con, this feature is not supported yet with Switch.
